import connectDB from './mongodb'
import Product from '@/models/Product'

const sampleProducts = [
  {
    name: 'Whey Protein Powder - Vanilla',
    slug: 'whey-protein-powder-vanilla',
    description: 'Premium whey protein powder packed with 25g of protein per serving. Perfect for post-workout recovery and muscle building. Made with high-quality ingredients and delicious vanilla flavor.',
    shortDescription: '25g protein per serving. Perfect for post-workout recovery.',
    price: 39.99,
    compareAtPrice: 49.99,
    sku: 'WHEY-VAN-001',
    images: ['/images/products/whey-protein.jpg'],
    category: 'supplements',
    tags: ['protein', 'whey', 'muscle-building', 'recovery'],
    inStock: true,
    stockQuantity: 50,
    weight: 2.27, // kg
    vendor: 'FitnessSupplies',
    vendorProductId: 'FIT-WHEY-001',
    status: 'active',
    featured: true,
    seoTitle: 'Whey Protein Powder - Vanilla | Premium Muscle Building Supplement',
    seoDescription: 'Buy premium whey protein powder with 25g protein per serving. Perfect for muscle building and recovery.',
  },
  {
    name: 'Pre-Workout Energy Boost',
    slug: 'pre-workout-energy-boost',
    description: 'High-performance pre-workout supplement designed to boost energy, focus, and endurance. Contains caffeine, beta-alanine, and creatine for maximum workout performance.',
    shortDescription: 'Boost energy and focus for intense workouts.',
    price: 29.99,
    compareAtPrice: 34.99,
    sku: 'PRE-EN-001',
    images: ['/images/products/pre-workout.jpg'],
    category: 'supplements',
    tags: ['pre-workout', 'energy', 'performance', 'caffeine'],
    inStock: true,
    stockQuantity: 30,
    weight: 0.5,
    vendor: 'FitnessSupplies',
    vendorProductId: 'FIT-PRE-001',
    status: 'active',
    featured: true,
    seoTitle: 'Pre-Workout Energy Boost | Maximum Performance Supplement',
    seoDescription: 'Enhance your workout performance with our premium pre-workout energy boost supplement.',
  },
  {
    name: 'Resistance Bands Set',
    slug: 'resistance-bands-set',
    description: 'Complete resistance bands set with 5 different resistance levels. Perfect for home workouts, travel, and full-body training. Includes door anchor and exercise guide.',
    shortDescription: '5-band set with door anchor. Perfect for home workouts.',
    price: 24.99,
    compareAtPrice: 29.99,
    sku: 'EQ-RB-001',
    images: ['/images/products/resistance-bands.jpg'],
    category: 'equipment',
    tags: ['resistance-bands', 'home-workout', 'equipment', 'portable'],
    inStock: true,
    stockQuantity: 100,
    weight: 0.5,
    dimensions: {
      length: 30,
      width: 20,
      height: 5,
    },
    vendor: 'FitnessGear',
    vendorProductId: 'GEAR-RB-001',
    status: 'active',
    featured: true,
    seoTitle: 'Resistance Bands Set | Home Workout Equipment',
    seoDescription: 'Complete resistance bands set with 5 resistance levels. Perfect for home workouts and travel.',
  },
  {
    name: 'Dumbbell Set - Adjustable',
    slug: 'dumbbell-set-adjustable',
    description: 'Adjustable dumbbell set from 5-50 lbs per dumbbell. Space-saving design perfect for home gyms. Includes stand and weight plates.',
    shortDescription: 'Adjustable 5-50 lbs per dumbbell. Space-saving design.',
    price: 199.99,
    compareAtPrice: 249.99,
    sku: 'EQ-DB-001',
    images: ['/images/products/dumbbells.jpg'],
    category: 'equipment',
    tags: ['dumbbells', 'weights', 'home-gym', 'strength-training'],
    inStock: true,
    stockQuantity: 25,
    weight: 22.68,
    dimensions: {
      length: 50,
      width: 30,
      height: 30,
    },
    vendor: 'FitnessGear',
    vendorProductId: 'GEAR-DB-001',
    status: 'active',
    featured: true,
    seoTitle: 'Adjustable Dumbbell Set | Home Gym Equipment',
    seoDescription: 'Adjustable dumbbell set 5-50 lbs. Perfect for home gym strength training.',
  },
  {
    name: 'Fitness Tank Top',
    slug: 'fitness-tank-top',
    description: 'Premium moisture-wicking tank top for men. Made with breathable fabric for maximum comfort during workouts. Available in multiple colors.',
    shortDescription: 'Moisture-wicking tank top. Breathable and comfortable.',
    price: 19.99,
    compareAtPrice: 24.99,
    sku: 'APP-TT-001',
    images: ['/images/products/tank-top.jpg'],
    category: 'apparel',
    tags: ['tank-top', 'men', 'workout', 'moisture-wicking'],
    inStock: true,
    stockQuantity: 150,
    weight: 0.2,
    vendor: 'FitnessApparel',
    vendorProductId: 'APP-TT-001',
    status: 'active',
    featured: false,
    seoTitle: 'Fitness Tank Top | Men\'s Workout Apparel',
    seoDescription: 'Premium moisture-wicking fitness tank top for men. Perfect for workouts.',
  },
  {
    name: 'Gym Bag - Large',
    slug: 'gym-bag-large',
    description: 'Spacious gym bag with multiple compartments. Water-resistant material with shoe compartment and laptop sleeve. Perfect for gym, travel, or daily use.',
    shortDescription: 'Large gym bag with multiple compartments. Water-resistant.',
    price: 34.99,
    compareAtPrice: 39.99,
    sku: 'ACC-GB-001',
    images: ['/images/products/gym-bag.jpg'],
    category: 'accessories',
    tags: ['gym-bag', 'bag', 'accessories', 'travel'],
    inStock: true,
    stockQuantity: 75,
    weight: 0.8,
    dimensions: {
      length: 50,
      width: 30,
      height: 30,
    },
    vendor: 'FitnessAccessories',
    vendorProductId: 'ACC-GB-001',
    status: 'active',
    featured: false,
    seoTitle: 'Large Gym Bag | Fitness Accessories',
    seoDescription: 'Spacious gym bag with multiple compartments. Perfect for gym and travel.',
  },
  {
    name: 'Creatine Monohydrate',
    slug: 'creatine-monohydrate',
    description: 'Pure creatine monohydrate powder. Helps increase strength and muscle mass. Unflavored, mixes easily. 100 servings per container.',
    shortDescription: 'Pure creatine monohydrate. Increases strength and muscle mass.',
    price: 16.99,
    compareAtPrice: 19.99,
    sku: 'SUP-CRE-001',
    images: ['/images/products/creatine.jpg'],
    category: 'supplements',
    tags: ['creatine', 'strength', 'muscle-building', 'supplement'],
    inStock: true,
    stockQuantity: 80,
    weight: 0.5,
    vendor: 'FitnessSupplies',
    vendorProductId: 'FIT-CRE-001',
    status: 'active',
    featured: true,
    seoTitle: 'Creatine Monohydrate | Strength Building Supplement',
    seoDescription: 'Pure creatine monohydrate powder. Helps increase strength and muscle mass.',
  },
  {
    name: 'Yoga Mat - Premium',
    slug: 'yoga-mat-premium',
    description: 'Extra-thick premium yoga mat with superior grip. Non-slip surface perfect for yoga, pilates, and stretching. Eco-friendly materials.',
    shortDescription: 'Extra-thick premium yoga mat with superior grip.',
    price: 29.99,
    compareAtPrice: 34.99,
    sku: 'EQ-YM-001',
    images: ['/images/products/yoga-mat.jpg'],
    category: 'equipment',
    tags: ['yoga-mat', 'yoga', 'fitness', 'exercise'],
    inStock: true,
    stockQuantity: 60,
    weight: 1.5,
    dimensions: {
      length: 183,
      width: 61,
      height: 1,
    },
    vendor: 'FitnessGear',
    vendorProductId: 'GEAR-YM-001',
    status: 'active',
    featured: false,
    seoTitle: 'Premium Yoga Mat | Extra-Thick Non-Slip',
    seoDescription: 'Extra-thick premium yoga mat with superior grip. Perfect for yoga and pilates.',
  },
]

async function main() {
  console.log('Starting product seed...')
  
  await connectDB()

  for (const productData of sampleProducts) {
    const product = await Product.findOneAndUpdate(
      { slug: productData.slug },
      productData,
      { upsert: true, new: true }
    )
    console.log(`✓ ${product.name}`)
  }

  console.log(`\nSeeded ${sampleProducts.length} products!`)
  process.exit(0)
}

main().catch((error) => {
  console.error('Error seeding products:', error)
  process.exit(1)
})

